### ISSUE TITLE
Would be good if this works for podcasts too.

### ISSUE THREAD

**Issue by vrishab** [donaghhorgan/rhythmbox-plugins-open-containing-folder#6]
Works great on latest Rhythmbox-3.4 ( debian unstable )

But, currently it works only for songs. Can you make the changes for podcasts too ? Thanks !

**Comment by donaghhorgan** [comment]
This seems like a bug (or deliberate restriction) in Rhythmbox itself. [`podcast-episode-popup`](https://github.com/GNOME/rhythmbox/blob/aea7e34b246b337d1755827f036224ff0c176eaa/data/ui/podcast-popups.ui) is added as a plugin location, so it should appear in the context menu on the Podcast page, but doesn't for some reason.

**Comment by vrishab** [comment]
Probably, the patch in  [ https://bugzilla.gnome.org/show_bug.cgi?id=773858 ]( https://bugzilla.gnome.org/show_bug.cgi?id=773858 )  should help.
