### ISSUE TITLE
Add option in plugin to decode actual filesystem path

### ISSUE THREAD

**Issue by vrishab** [donaghhorgan/rhythmbox-plugins-open-containing-folder#7]
I have all my songs in external drive. I just create a symlink in ~/Music for rhythmbox to pick up the songs. Currently the plugin opens the symlink path. If possible, add an option to open the actual path in plugin preferences. Thanks !

**Comment by vrishab** [comment]
Something like the following:

import os
real_path = os.path.realpath("symlink_path")

**Comment by donaghhorgan** [comment]
Fixed by ea42c011a2e1ed60150a22bf51028e1a2c6fded6.
