### ISSUE TITLE
Incorrect folder shown for podcasts in play queue

### ISSUE THREAD

**Issue by vrishab** [donaghhorgan/rhythmbox-plugins-open-containing-folder#9]
Steps to reproduce:
1. Add podcasts to play queue.
2. Get containing folder for a podcast entry. It shows Music folder ( which is podcast download folder ), which is common for all podcast entries.

**Comment by donaghhorgan** [comment]
I can't reproduce this. I'm following these steps:

1. Download a podcast (I got This American Life #595).
2. Add the podcast to the play queue.
3. Move to the Play Queue tab.
4. Open the containing folder of the podcast using the right click context menu.

When I follow these steps, I see the folder `/home/donagh/Podcasts/This American Life`.

**Comment by vrishab** [comment]
Can close this issue.
